// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Delivery/grpc/timeseries_grpc/timeSeries.proto

/*
Package timeseries_grpc is a generated protocol buffer package.

It is generated from these files:
	Delivery/grpc/timeseries_grpc/timeSeries.proto

It has these top-level messages:
	Value
	Timeseries
	GetAllFromTimeToTimeRequest
	GetAllFromTimeToTimeResponse
	Error
*/
package timeseries_grpc

import (
	fmt "fmt"

	proto "github.com/golang/protobuf/proto"

	math "math"

	google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

	context "golang.org/x/net/context"

	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Value struct {
	Hour  *google_protobuf.Timestamp `protobuf:"bytes,1,opt,name=hour" json:"hour,omitempty"`
	Value float64                    `protobuf:"fixed64,2,opt,name=value" json:"value,omitempty"`
}

func (m *Value) Reset()                    { *m = Value{} }
func (m *Value) String() string            { return proto.CompactTextString(m) }
func (*Value) ProtoMessage()               {}
func (*Value) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Value) GetHour() *google_protobuf.Timestamp {
	if m != nil {
		return m.Hour
	}
	return nil
}

func (m *Value) GetValue() float64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type Timeseries struct {
	Id         string                     `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	MeterId    string                     `protobuf:"bytes,2,opt,name=meterId" json:"meterId,omitempty"`
	CustomerId string                     `protobuf:"bytes,3,opt,name=customerId" json:"customerId,omitempty"`
	Resolution string                     `protobuf:"bytes,4,opt,name=resolution" json:"resolution,omitempty"`
	From       *google_protobuf.Timestamp `protobuf:"bytes,5,opt,name=from" json:"from,omitempty"`
	To         *google_protobuf.Timestamp `protobuf:"bytes,6,opt,name=to" json:"to,omitempty"`
	Values     []*Value                   `protobuf:"bytes,7,rep,name=values" json:"values,omitempty"`
}

func (m *Timeseries) Reset()                    { *m = Timeseries{} }
func (m *Timeseries) String() string            { return proto.CompactTextString(m) }
func (*Timeseries) ProtoMessage()               {}
func (*Timeseries) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Timeseries) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Timeseries) GetMeterId() string {
	if m != nil {
		return m.MeterId
	}
	return ""
}

func (m *Timeseries) GetCustomerId() string {
	if m != nil {
		return m.CustomerId
	}
	return ""
}

func (m *Timeseries) GetResolution() string {
	if m != nil {
		return m.Resolution
	}
	return ""
}

func (m *Timeseries) GetFrom() *google_protobuf.Timestamp {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *Timeseries) GetTo() *google_protobuf.Timestamp {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *Timeseries) GetValues() []*Value {
	if m != nil {
		return m.Values
	}
	return nil
}

type GetAllFromTimeToTimeRequest struct {
	From       *google_protobuf.Timestamp `protobuf:"bytes,1,opt,name=from" json:"from,omitempty"`
	To         *google_protobuf.Timestamp `protobuf:"bytes,2,opt,name=to" json:"to,omitempty"`
	CustomerId string                     `protobuf:"bytes,3,opt,name=customerId" json:"customerId,omitempty"`
	MeterId    string                     `protobuf:"bytes,4,opt,name=meterId" json:"meterId,omitempty"`
}

func (m *GetAllFromTimeToTimeRequest) Reset()                    { *m = GetAllFromTimeToTimeRequest{} }
func (m *GetAllFromTimeToTimeRequest) String() string            { return proto.CompactTextString(m) }
func (*GetAllFromTimeToTimeRequest) ProtoMessage()               {}
func (*GetAllFromTimeToTimeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetAllFromTimeToTimeRequest) GetFrom() *google_protobuf.Timestamp {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *GetAllFromTimeToTimeRequest) GetTo() *google_protobuf.Timestamp {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *GetAllFromTimeToTimeRequest) GetCustomerId() string {
	if m != nil {
		return m.CustomerId
	}
	return ""
}

func (m *GetAllFromTimeToTimeRequest) GetMeterId() string {
	if m != nil {
		return m.MeterId
	}
	return ""
}

type GetAllFromTimeToTimeResponse struct {
	TimeseriesList []*Timeseries `protobuf:"bytes,1,rep,name=TimeseriesList" json:"TimeseriesList,omitempty"`
}

func (m *GetAllFromTimeToTimeResponse) Reset()                    { *m = GetAllFromTimeToTimeResponse{} }
func (m *GetAllFromTimeToTimeResponse) String() string            { return proto.CompactTextString(m) }
func (*GetAllFromTimeToTimeResponse) ProtoMessage()               {}
func (*GetAllFromTimeToTimeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetAllFromTimeToTimeResponse) GetTimeseriesList() []*Timeseries {
	if m != nil {
		return m.TimeseriesList
	}
	return nil
}

type Error struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *Error) Reset()                    { *m = Error{} }
func (m *Error) String() string            { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()               {}
func (*Error) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Value)(nil), "timeseries_grpc.Value")
	proto.RegisterType((*Timeseries)(nil), "timeseries_grpc.Timeseries")
	proto.RegisterType((*GetAllFromTimeToTimeRequest)(nil), "timeseries_grpc.GetAllFromTimeToTimeRequest")
	proto.RegisterType((*GetAllFromTimeToTimeResponse)(nil), "timeseries_grpc.GetAllFromTimeToTimeResponse")
	proto.RegisterType((*Error)(nil), "timeseries_grpc.Error")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for TimeseriesHandler service

type TimeseriesHandlerClient interface {
	Store(ctx context.Context, in *Timeseries, opts ...grpc.CallOption) (*Timeseries, error)
	// TODO get all timeseries for a period of time
	GetAllFromTimeToTime(ctx context.Context, in *GetAllFromTimeToTimeRequest, opts ...grpc.CallOption) (*GetAllFromTimeToTimeResponse, error)
}

type timeseriesHandlerClient struct {
	cc *grpc.ClientConn
}

func NewTimeseriesHandlerClient(cc *grpc.ClientConn) TimeseriesHandlerClient {
	return &timeseriesHandlerClient{cc}
}

func (c *timeseriesHandlerClient) Store(ctx context.Context, in *Timeseries, opts ...grpc.CallOption) (*Timeseries, error) {
	out := new(Timeseries)
	err := grpc.Invoke(ctx, "/timeseries_grpc.timeseriesHandler/Store", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timeseriesHandlerClient) GetAllFromTimeToTime(ctx context.Context, in *GetAllFromTimeToTimeRequest, opts ...grpc.CallOption) (*GetAllFromTimeToTimeResponse, error) {
	out := new(GetAllFromTimeToTimeResponse)
	err := grpc.Invoke(ctx, "/timeseries_grpc.timeseriesHandler/GetAllFromTimeToTime", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for TimeseriesHandler service

type TimeseriesHandlerServer interface {
	Store(context.Context, *Timeseries) (*Timeseries, error)
	// TODO get all timeseries for a period of time
	GetAllFromTimeToTime(context.Context, *GetAllFromTimeToTimeRequest) (*GetAllFromTimeToTimeResponse, error)
}

func RegisterTimeseriesHandlerServer(s *grpc.Server, srv TimeseriesHandlerServer) {
	s.RegisterService(&_TimeseriesHandler_serviceDesc, srv)
}

func _TimeseriesHandler_Store_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Timeseries)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimeseriesHandlerServer).Store(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/timeseries_grpc.timeseriesHandler/Store",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimeseriesHandlerServer).Store(ctx, req.(*Timeseries))
	}
	return interceptor(ctx, in, info, handler)
}

func _TimeseriesHandler_GetAllFromTimeToTime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllFromTimeToTimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimeseriesHandlerServer).GetAllFromTimeToTime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/timeseries_grpc.timeseriesHandler/GetAllFromTimeToTime",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimeseriesHandlerServer).GetAllFromTimeToTime(ctx, req.(*GetAllFromTimeToTimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TimeseriesHandler_serviceDesc = grpc.ServiceDesc{
	ServiceName: "timeseries_grpc.timeseriesHandler",
	HandlerType: (*TimeseriesHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Store",
			Handler:    _TimeseriesHandler_Store_Handler,
		},
		{
			MethodName: "GetAllFromTimeToTime",
			Handler:    _TimeseriesHandler_GetAllFromTimeToTime_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Delivery/grpc/timeseries_grpc/timeSeries.proto",
}

func init() { proto.RegisterFile("Delivery/grpc/timeseries_grpc/timeSeries.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 399 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0xdd, 0xca, 0xda, 0x40,
	0x14, 0xfc, 0x36, 0x9f, 0x51, 0x3c, 0x82, 0xa5, 0x8b, 0x94, 0x25, 0x96, 0xd6, 0xe6, 0x4a, 0x4a,
	0xbb, 0x82, 0x7d, 0x82, 0x62, 0x7f, 0xa1, 0xbd, 0x89, 0xd2, 0xdb, 0x12, 0xcd, 0x31, 0x0d, 0x24,
	0x9e, 0x74, 0x77, 0x23, 0xf4, 0xb6, 0xaf, 0xd4, 0x07, 0xe9, 0x2b, 0x95, 0x6c, 0x8c, 0xb1, 0x2a,
	0xea, 0x77, 0x13, 0x38, 0x3b, 0x33, 0x27, 0xb3, 0x33, 0x0b, 0xf2, 0x1d, 0xa6, 0xc9, 0x16, 0xd5,
	0xaf, 0x49, 0xac, 0xf2, 0xd5, 0xc4, 0x24, 0x19, 0x6a, 0x54, 0x09, 0xea, 0xef, 0xfb, 0x79, 0x6e,
	0x67, 0x99, 0x2b, 0x32, 0xc4, 0x1f, 0x1d, 0x31, 0xbc, 0xe7, 0x31, 0x51, 0x9c, 0xe2, 0xc4, 0xc2,
	0xcb, 0x62, 0x5d, 0xad, 0x30, 0x61, 0x96, 0x57, 0x0a, 0xff, 0x2b, 0xb8, 0xdf, 0xc2, 0xb4, 0x40,
	0x2e, 0xa1, 0xf5, 0x83, 0x0a, 0x25, 0xd8, 0x88, 0x8d, 0x7b, 0x53, 0x4f, 0x56, 0x42, 0x59, 0x0b,
	0xe5, 0xa2, 0x16, 0x06, 0x96, 0xc7, 0x07, 0xe0, 0x6e, 0x4b, 0xa1, 0x70, 0x46, 0x6c, 0xcc, 0x82,
	0x6a, 0xf0, 0x7f, 0x3b, 0x00, 0x8b, 0xbd, 0x07, 0xde, 0x07, 0x27, 0x89, 0xec, 0xca, 0x6e, 0xe0,
	0x24, 0x11, 0x17, 0xd0, 0xc9, 0xd0, 0xa0, 0xfa, 0x1c, 0x59, 0x59, 0x37, 0xa8, 0x47, 0xfe, 0x0c,
	0x60, 0x55, 0x68, 0x43, 0x99, 0x05, 0xef, 0x2d, 0x78, 0x70, 0x52, 0xe2, 0x0a, 0x35, 0xa5, 0x85,
	0x49, 0x68, 0x23, 0x5a, 0x15, 0xde, 0x9c, 0x94, 0xf6, 0xd7, 0x8a, 0x32, 0xe1, 0x5e, 0xb7, 0x5f,
	0xf2, 0xf8, 0x4b, 0x70, 0x0c, 0x89, 0xf6, 0x55, 0xb6, 0x63, 0x88, 0x4b, 0x68, 0xdb, 0xdb, 0x69,
	0xd1, 0x19, 0xdd, 0x8f, 0x7b, 0xd3, 0x27, 0xf2, 0x28, 0x66, 0x69, 0x23, 0x0c, 0x76, 0x2c, 0xff,
	0x0f, 0x83, 0xe1, 0x47, 0x34, 0x6f, 0xd3, 0xf4, 0x83, 0xa2, 0xac, 0xdc, 0xb5, 0xa0, 0xf2, 0x1b,
	0xe0, 0xcf, 0x02, 0xb5, 0xd9, 0x7b, 0x65, 0x0f, 0xf2, 0xea, 0xdc, 0xe4, 0xf5, 0x5a, 0x8e, 0x07,
	0x0d, 0xb4, 0xfe, 0x6b, 0xc0, 0x5f, 0xc1, 0xd3, 0xf3, 0xa6, 0x75, 0x4e, 0x1b, 0x8d, 0x7c, 0x06,
	0xfd, 0xa6, 0xd9, 0x2f, 0x89, 0x36, 0x82, 0xd9, 0x34, 0x86, 0x27, 0x69, 0x34, 0xb4, 0xe0, 0x48,
	0xe2, 0xbf, 0x00, 0xf7, 0xbd, 0x52, 0xa4, 0x2a, 0x1f, 0x5a, 0x87, 0x31, 0xee, 0x9e, 0x47, 0x3d,
	0x4e, 0xff, 0x32, 0x78, 0xdc, 0x6c, 0xfc, 0x14, 0x6e, 0xa2, 0x14, 0x15, 0x9f, 0x81, 0x3b, 0x37,
	0xa4, 0x90, 0x5f, 0xfa, 0x9d, 0x77, 0x09, 0xf4, 0xef, 0x78, 0x01, 0x83, 0x73, 0x57, 0xe4, 0xaf,
	0x4e, 0x64, 0x17, 0xea, 0xf3, 0x5e, 0xdf, 0xc8, 0xae, 0x72, 0xf3, 0xef, 0x96, 0x6d, 0xdb, 0xd5,
	0x9b, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x2e, 0xb0, 0x54, 0x7c, 0xce, 0x03, 0x00, 0x00,
}
