// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Delivery/grpc/timeseries_grpc/timeSeries.proto

/*
Package timeseries_grpc is a generated protocol buffer package.

It is generated from these files:
	Delivery/grpc/timeseries_grpc/timeSeries.proto

It has these top-level messages:
	Timeseries
	GetAllFromTimeToTimeRequest
	GetAllFromTimeToTimeResponse
	Error
*/
package timeseries_grpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Timeseries struct {
	Id         string             `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	MeterId    string             `protobuf:"bytes,2,opt,name=meterId" json:"meterId,omitempty"`
	CustomerId string             `protobuf:"bytes,3,opt,name=customerId" json:"customerId,omitempty"`
	Resolution string             `protobuf:"bytes,4,opt,name=resolution" json:"resolution,omitempty"`
	From       string             `protobuf:"bytes,5,opt,name=from" json:"from,omitempty"`
	To         string             `protobuf:"bytes,6,opt,name=to" json:"to,omitempty"`
	Values     map[string]float64 `protobuf:"bytes,7,rep,name=values" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
}

func (m *Timeseries) Reset()                    { *m = Timeseries{} }
func (m *Timeseries) String() string            { return proto.CompactTextString(m) }
func (*Timeseries) ProtoMessage()               {}
func (*Timeseries) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Timeseries) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Timeseries) GetMeterId() string {
	if m != nil {
		return m.MeterId
	}
	return ""
}

func (m *Timeseries) GetCustomerId() string {
	if m != nil {
		return m.CustomerId
	}
	return ""
}

func (m *Timeseries) GetResolution() string {
	if m != nil {
		return m.Resolution
	}
	return ""
}

func (m *Timeseries) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *Timeseries) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *Timeseries) GetValues() map[string]float64 {
	if m != nil {
		return m.Values
	}
	return nil
}

type GetAllFromTimeToTimeRequest struct {
	From       string `protobuf:"bytes,1,opt,name=from" json:"from,omitempty"`
	To         string `protobuf:"bytes,2,opt,name=to" json:"to,omitempty"`
	CustomerId string `protobuf:"bytes,3,opt,name=customerId" json:"customerId,omitempty"`
	MeterId    string `protobuf:"bytes,4,opt,name=meterId" json:"meterId,omitempty"`
}

func (m *GetAllFromTimeToTimeRequest) Reset()                    { *m = GetAllFromTimeToTimeRequest{} }
func (m *GetAllFromTimeToTimeRequest) String() string            { return proto.CompactTextString(m) }
func (*GetAllFromTimeToTimeRequest) ProtoMessage()               {}
func (*GetAllFromTimeToTimeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetAllFromTimeToTimeRequest) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *GetAllFromTimeToTimeRequest) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *GetAllFromTimeToTimeRequest) GetCustomerId() string {
	if m != nil {
		return m.CustomerId
	}
	return ""
}

func (m *GetAllFromTimeToTimeRequest) GetMeterId() string {
	if m != nil {
		return m.MeterId
	}
	return ""
}

type GetAllFromTimeToTimeResponse struct {
	TimeseriesList []*Timeseries `protobuf:"bytes,1,rep,name=TimeseriesList" json:"TimeseriesList,omitempty"`
}

func (m *GetAllFromTimeToTimeResponse) Reset()                    { *m = GetAllFromTimeToTimeResponse{} }
func (m *GetAllFromTimeToTimeResponse) String() string            { return proto.CompactTextString(m) }
func (*GetAllFromTimeToTimeResponse) ProtoMessage()               {}
func (*GetAllFromTimeToTimeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetAllFromTimeToTimeResponse) GetTimeseriesList() []*Timeseries {
	if m != nil {
		return m.TimeseriesList
	}
	return nil
}

type Error struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *Error) Reset()                    { *m = Error{} }
func (m *Error) String() string            { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()               {}
func (*Error) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Timeseries)(nil), "timeseries_grpc.Timeseries")
	proto.RegisterType((*GetAllFromTimeToTimeRequest)(nil), "timeseries_grpc.GetAllFromTimeToTimeRequest")
	proto.RegisterType((*GetAllFromTimeToTimeResponse)(nil), "timeseries_grpc.GetAllFromTimeToTimeResponse")
	proto.RegisterType((*Error)(nil), "timeseries_grpc.Error")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for TimeseriesHandler service

type TimeseriesHandlerClient interface {
	Store(ctx context.Context, in *Timeseries, opts ...grpc.CallOption) (*Timeseries, error)
	// TODO get all timeseries for a period of time
	GetAllFromTimeToTime(ctx context.Context, in *GetAllFromTimeToTimeRequest, opts ...grpc.CallOption) (*GetAllFromTimeToTimeResponse, error)
}

type timeseriesHandlerClient struct {
	cc *grpc.ClientConn
}

func NewTimeseriesHandlerClient(cc *grpc.ClientConn) TimeseriesHandlerClient {
	return &timeseriesHandlerClient{cc}
}

func (c *timeseriesHandlerClient) Store(ctx context.Context, in *Timeseries, opts ...grpc.CallOption) (*Timeseries, error) {
	out := new(Timeseries)
	err := grpc.Invoke(ctx, "/timeseries_grpc.timeseriesHandler/Store", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timeseriesHandlerClient) GetAllFromTimeToTime(ctx context.Context, in *GetAllFromTimeToTimeRequest, opts ...grpc.CallOption) (*GetAllFromTimeToTimeResponse, error) {
	out := new(GetAllFromTimeToTimeResponse)
	err := grpc.Invoke(ctx, "/timeseries_grpc.timeseriesHandler/GetAllFromTimeToTime", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for TimeseriesHandler service

type TimeseriesHandlerServer interface {
	Store(context.Context, *Timeseries) (*Timeseries, error)
	// TODO get all timeseries for a period of time
	GetAllFromTimeToTime(context.Context, *GetAllFromTimeToTimeRequest) (*GetAllFromTimeToTimeResponse, error)
}

func RegisterTimeseriesHandlerServer(s *grpc.Server, srv TimeseriesHandlerServer) {
	s.RegisterService(&_TimeseriesHandler_serviceDesc, srv)
}

func _TimeseriesHandler_Store_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Timeseries)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimeseriesHandlerServer).Store(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/timeseries_grpc.timeseriesHandler/Store",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimeseriesHandlerServer).Store(ctx, req.(*Timeseries))
	}
	return interceptor(ctx, in, info, handler)
}

func _TimeseriesHandler_GetAllFromTimeToTime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllFromTimeToTimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimeseriesHandlerServer).GetAllFromTimeToTime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/timeseries_grpc.timeseriesHandler/GetAllFromTimeToTime",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimeseriesHandlerServer).GetAllFromTimeToTime(ctx, req.(*GetAllFromTimeToTimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TimeseriesHandler_serviceDesc = grpc.ServiceDesc{
	ServiceName: "timeseries_grpc.timeseriesHandler",
	HandlerType: (*TimeseriesHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Store",
			Handler:    _TimeseriesHandler_Store_Handler,
		},
		{
			MethodName: "GetAllFromTimeToTime",
			Handler:    _TimeseriesHandler_GetAllFromTimeToTime_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Delivery/grpc/timeseries_grpc/timeSeries.proto",
}

func init() { proto.RegisterFile("Delivery/grpc/timeseries_grpc/timeSeries.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 373 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0xcd, 0x4e, 0xea, 0x40,
	0x14, 0xa6, 0x85, 0x42, 0xee, 0x21, 0xe1, 0xde, 0x3b, 0x61, 0x31, 0x81, 0x9b, 0x1b, 0xec, 0x46,
	0x16, 0x5a, 0x12, 0xdc, 0xa8, 0x1b, 0x63, 0x10, 0x7f, 0x12, 0x57, 0x85, 0xb8, 0x35, 0x48, 0x8f,
	0xa4, 0xb1, 0xed, 0xe0, 0x99, 0x29, 0x09, 0xf1, 0x3d, 0x7c, 0x2d, 0x5f, 0xc9, 0x74, 0x0a, 0x2d,
	0x02, 0xa9, 0x6e, 0x9a, 0x39, 0xdf, 0x77, 0xa6, 0xdf, 0x4f, 0x53, 0x70, 0xae, 0x30, 0xf0, 0x17,
	0x48, 0xcb, 0xde, 0x8c, 0xe6, 0xd3, 0x9e, 0xf2, 0x43, 0x94, 0x48, 0x3e, 0xca, 0xc7, 0x6c, 0x1e,
	0xe9, 0xd9, 0x99, 0x93, 0x50, 0x82, 0xfd, 0xde, 0xda, 0xb0, 0xdf, 0x4d, 0x80, 0x71, 0x86, 0xb1,
	0x06, 0x98, 0xbe, 0xc7, 0x8d, 0x8e, 0xd1, 0xfd, 0xe5, 0x9a, 0xbe, 0xc7, 0x38, 0xd4, 0x42, 0x54,
	0x48, 0x77, 0x1e, 0x37, 0x35, 0xb8, 0x1e, 0xd9, 0x7f, 0x80, 0x69, 0x2c, 0x95, 0x08, 0x35, 0x59,
	0xd6, 0xe4, 0x06, 0x92, 0xf0, 0x84, 0x52, 0x04, 0xb1, 0xf2, 0x45, 0xc4, 0x2b, 0x29, 0x9f, 0x23,
	0x8c, 0x41, 0xe5, 0x99, 0x44, 0xc8, 0x2d, 0xcd, 0xe8, 0x73, 0xa2, 0xae, 0x04, 0xaf, 0xa6, 0xea,
	0x4a, 0xb0, 0x0b, 0xa8, 0x2e, 0x26, 0x41, 0x8c, 0x92, 0xd7, 0x3a, 0xe5, 0x6e, 0xbd, 0x7f, 0xe8,
	0x6c, 0xd9, 0x77, 0x72, 0xeb, 0xce, 0x83, 0xde, 0x1c, 0x46, 0x8a, 0x96, 0xee, 0xea, 0x5a, 0xeb,
	0x0c, 0xea, 0x1b, 0x30, 0xfb, 0x03, 0xe5, 0x17, 0x5c, 0xae, 0xe2, 0x25, 0x47, 0xd6, 0x04, 0x4b,
	0xaf, 0xea, 0x74, 0x86, 0x9b, 0x0e, 0xe7, 0xe6, 0xa9, 0x61, 0xbf, 0x41, 0xfb, 0x06, 0xd5, 0x65,
	0x10, 0x5c, 0x93, 0x08, 0x13, 0x99, 0xb1, 0x48, 0x9e, 0x2e, 0xbe, 0xc6, 0x28, 0x55, 0x66, 0xdf,
	0xd8, 0xb1, 0x6f, 0x66, 0xf6, 0xbf, 0xab, 0x68, 0xa3, 0xdc, 0xca, 0x97, 0x72, 0xed, 0x29, 0xfc,
	0xdb, 0x2f, 0x2e, 0xe7, 0x22, 0x92, 0xc8, 0x06, 0xd0, 0xc8, 0x93, 0xdf, 0xfb, 0x52, 0x71, 0x43,
	0x17, 0xd4, 0x2e, 0x28, 0xc8, 0xdd, 0xba, 0x62, 0x1f, 0x80, 0x35, 0x24, 0x12, 0x94, 0xfa, 0x90,
	0x72, 0x32, 0xc3, 0x55, 0x9c, 0xf5, 0xd8, 0xff, 0x30, 0xe0, 0x6f, 0xfe, 0xc6, 0xdb, 0x49, 0xe4,
	0x05, 0x48, 0x6c, 0x00, 0xd6, 0x48, 0x09, 0x42, 0x56, 0x24, 0xd7, 0x2a, 0x22, 0xed, 0x12, 0x8b,
	0xa1, 0xb9, 0x2f, 0x22, 0x3b, 0xda, 0xb9, 0x56, 0xf0, 0x19, 0x5a, 0xc7, 0x3f, 0xdc, 0x4e, 0x7b,
	0xb3, 0x4b, 0x4f, 0x55, 0xfd, 0x1f, 0x9c, 0x7c, 0x06, 0x00, 0x00, 0xff, 0xff, 0x4f, 0xb3, 0x33,
	0x31, 0x39, 0x03, 0x00, 0x00,
}
